version: "3.8"
name: cos30049-eth-visualization
services:
  neo4j:
    image: neo4j:latest
    env_file:
      - neo4j.env
    ports:
      - 7687:7687
    volumes:
      - .tmp/neo4j/tmp/data:/data

  nextjs:
    depends_on:
      - neo4j
    ports:
      - 3000:3000 # Next.js application
      - 9229:9229 # Node.js debug port
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NEO4J_URI=${NEO4J_URI}
        - NEO4J_USERNAME=${NEO4J_USERNAME}
        - NEO4J_PASSWORD=${NEO4J_PASSWORD}
        - NEO4J_DB=${NEO4J_USERNAME}
    env_file:
      - app.env
    volumes:
      - .tmp/nextjs:/app

  seed:
    depends_on:
      - neo4j
    build:
      context: ./setup
      dockerfile: Dockerfile
    env_file:
      - app.env

