import "./globals.css";
import { Text } from "@tremor/react";
import type { Metadata } from "next";
import ThemeProvider from "./theme-provider";
import { ApolloClientProvider } from "./apollo/client-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="container mx-auto flex flex-col h-screen justify-between">
        <ApolloClientProvider>
          {/* <ThemeProvider> */}
          {children}
          {/* </ThemeProvider> */}
        </ApolloClientProvider>
        <footer className="footer footer-center w-full p-6">
          <div className="text-center">
            <Text>
              Copyright © 2022 -<a className="font-semibold"> bancorp</a>
            </Text>
          </div>
        </footer>
      </body>
    </html>
  );
};

export default RootLayout;
