import type { Metadata } from "next";

import Footer from "@/components/home/Footer";
import Header from "@/components/home/Navbar";
import Hero from "@/components/home/Hero";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

/** Homepage */
const Home = () => {
	return (
		<div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
			<Header />
			<main className="grow">
				<Hero />
			</main>
			<Footer />
		</div>
	);
};

export default Home;
