""""
Address Types for Addresses. Either eoa (Externally Owned Account) or contracts
"""
enum AddressType {
  eoa
  contract
}

"""
Represents an Ethereum Address
"""
type Address {
  """
  An Ethereum address is a 42-character hexadecimal address
  """
  address: String!
  
  """
  Type of Ethereum address
  """
  type: AddressType

  """
  Transactions where the address is the receiving party
  """
  bought: [Transaction!]! @relationship(type: "BUY", direction: OUT)
  
  """
  Transactions where the address is the sending party
  """
  sold: [Transaction!]! @relationship(type: "SELL", direction: OUT)
}

"""
Represents an Ethereum Transaction
"""
type Transaction {
  """
  Transaction block hash
  """
  block_hash: String!

  """
  Number of the block in which the transaction is recorded. Block confirmations indicate how many blocks have been added since the transaction was produced
  """
  block_number: Int!

  """
  The date and time at which a transaction is produced
  """
  block_timestamp: DateTime!

  """
  Maximum amount of gas allocated for the transaction. Normal ETH transfers involve 21,000 gas units while contracts involve higher values
  """
  gas: Float!

  """
  Cost per unit of gas spent for the transaction
  """
  gas_price: Float!

  """
  Amount of gas used by the transaction
  """
  gas_used: Float!
  
  """
  A TxHash or transaction hash is a unique 66-character identifier that is generated whenever a transaction is executed
  """
  hash: String!

  """
  Additional data included for this transaction. Commonly used as part of contract interaction or as a message sent to the recipient
  """
  input: String!

  """
  Amount paid to process the transaction in Wei
  """
  transaction_fee: Float!


  transaction_index: Int!

  """
  Value of Ethereum of the transaction
  """
  value: Float!

  """
  Sending party of the transaction
  """
  from_address: Address! @relationship(type: "SELL", direction: IN)

  """
  Receiving party of the transaction
  """
  to_address: Address! @relationship(type: "BUY", direction: IN)
}

type NumberAggregate {
  sum: Float!
  average: Float!
  min: Float!
  max: Float!
}

type VolumeStat {
  year: Int
  month: Int
  day: Int
  count: Int
  value: NumberAggregate
}

type DistributionStat {
  total: Int!
  min: Float!
  minNonZero: Float!
  max: Float!
  mean: Float!
  stdev: Float!
}

type TransactionCount {
  address: Address
  count: Int!
}

type TransactionEdgeAggregate {
  from_address: Address
  to_address: Address
  count: Int
  value: NumberAggregate
}

type TransactionAddressTypeAggregate {
  type: AddressType
  count: Int
  value: NumberAggregate
}

type Query {
  getTopBuyAddresses(limit: Int): [TransactionCount]
    @cypher(
      statement: """
      MATCH (a:Address)-[:BUY]-(t:Transaction)
      WITH a.address as address,
      a.type as type,
      count(t) AS bought
      RETURN {
        address: {
            address: address,
            type: type
        },
        count: bought
      } as result
      ORDER BY bought DESC LIMIT 5
      """
      columnName: "result"
    )

  getTopSellAddresses(limit: Int): [TransactionCount]
    @cypher(
      statement: """
      MATCH (a:Address)-[:SELL]-(t:Transaction)
      WITH a.address as address,
      a.type as type,
      count(t) AS sold
      RETURN {
        address: {
            address: address,
            type: type
        },
        count: sold
      } as result
      ORDER BY sold DESC LIMIT $limit
      """
      columnName: "result"
    )

  transactionAddressTypeAggregate: [TransactionAddressTypeAggregate]
    @cypher(
      statement: """
      MATCH
        (t:Transaction)-[:BUY|:SELL]-(a:Address)
      WITH
        count(t)/2 as transactionsCount,
        sum(t.value) as totalValue,
        avg(t.value) as averageValue,
        min(t.value) as minValue,
        max(t.value) as maxValue,
        a.type as type
      RETURN {
        type: type,
        count: transactionsCount,
        value: {
          sum: totalValue,
          average: averageValue,
          min: minValue,
          max: maxValue
        }
      } as result
      """
      columnName: "result"
    )

  getYearlyVolume: [VolumeStat]
    @cypher(
      statement: """
      MATCH (transaction:Transaction)
      WITH
        transaction.block_timestamp.year as year,
        count(*) as transactionsCount,
        sum(transaction.value) as totalValue,
        avg(transaction.value) as averageValue,
        min(transaction.value) as minValue,
        max(transaction.value) as maxValue
      RETURN {
        year: year,
        count: transactionsCount,
        value: {
          sum: totalValue,
          average: averageValue,
          min: minValue,
          max: maxValue
        }
      } as result
      """
      columnName: "result"
    )

  getMonthlyVolume: [VolumeStat]
    @cypher(
      statement: """
      MATCH (transaction:Transaction)
      WITH
        transaction.block_timestamp.month as month,
        transaction.block_timestamp.year as year,
        count(*) as transactionsCount,
        sum(transaction.value) as totalValue,
        avg(transaction.value) as averageValue,
        min(transaction.value) as minValue,
        max(transaction.value) as maxValue
      ORDER BY COALESCE(month ,"") + '/' + COALESCE(year ,"") ASC
      RETURN
      {
        year: year,
        month: month,
        count: transactionsCount,
        value: {
          sum: totalValue,
          average: averageValue,
          min: minValue,
          max: maxValue
        }
      } as result
      """
      columnName: "result"
    )

  getValueDistribution: DistributionStat
    @cypher(
      statement: """
      MATCH (t:Transaction)
      RETURN apoc.agg.statistics(t.value) AS result
      """
      columnName: "result"
    )

  getGasPriceDistribution: DistributionStat
    @cypher(
      statement: """
      MATCH (t:Transaction)
      RETURN apoc.agg.statistics(t.gas_price) AS result
      """
      columnName: "result"
    )

  transactionEdgeAggregate(address: String): [TransactionEdgeAggregate]
    @cypher(
      statement: """
      MATCH
        (t:Transaction),
        (t)<-[:SELL]-(seller:Address{address:$address}),
        (t)<-[:BUY]-(buyer:Address)
      WITH
        seller,
        collect(DISTINCT buyer) as buyers
      UNWIND buyers as buyer
      MATCH
        (t:Transaction),
        (t)<-[:SELL]-(seller),
        (t)<-[:BUY]-(buyer)
      WITH
        seller,
        buyer,
        count(t) as transactionsCount,
        sum(t.value) as totalValue,
        avg(t.value) as averageValue,
        min(t.value) as minValue,
        max(t.value) as maxValue
      RETURN {
        from_address: {
          address: seller.address,
          type: seller.type
        },
        to_address: {
          address: buyer.address,
          type: buyer.type
        },
        count: transactionsCount,
        value: {
          sum: totalValue,
          average: averageValue,
          min: minValue,
          max: maxValue
        }
      } as result

      UNION

      MATCH
        (t:Transaction),
        (t)<-[:SELL]-(seller:Address),
        (t)<-[:BUY]-(buyer:Address{address:$address})
      WITH
        buyer,
        collect(DISTINCT seller) as sellers
      UNWIND sellers as seller
      MATCH
        (t:Transaction),
        (t)<-[:SELL]-(seller),
        (t)<-[:BUY]-(buyer)
      WITH
        seller,
        buyer,
        count(t) as transactionsCount,
        sum(t.value) as totalValue,
        avg(t.value) as averageValue,
        min(t.value) as minValue,
        max(t.value) as maxValue
      RETURN {
        from_address: {
          address: seller.address,
          type: seller.type
        },
        to_address: {
          address: buyer.address,
          type: buyer.type
        },
        count: transactionsCount,
        value: {
          sum: totalValue,
          average: averageValue,
          min: minValue,
          max: maxValue
        }
      } as result
      """
      columnName: "result"
    )
}
