query GetTopAddresses {
  getTopBuyAddresses {
    address {
      address
    }
    count
  }

#   getTopSellAddresses {
#     address {
#       address
#     }
#     count
#   }

  transactionAddressTypeAggregate {
    type
    count
  }
}
