
query GetBoughtStat($address: String) {
  addresses(where: { address: $address }) {
    boughtAggregate {
      count
      node {
        value {
          sum
          min
          max
        }
      }
    }
  }
}
