query GetFullAddressStat($address: String) {
  addresses(where: { address: $address }) {
    address
    type
    boughtAggregate {
      count
      node {
        value {
          sum
        }
      }
    }
    soldAggregate {
      count
      node {
        value {
          sum
        }
      }
    }
  }
}
